# Generated by Django 3.1.2 on 2020-10-24 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20201017_2255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessages',
            old_name='sender_id',
            new_name='sender',
        ),
    ]
