# Generated by Django 3.1.2 on 2020-10-16 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chat_is_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'verbose_name_plural': 'Chats'},
        ),
        migrations.AlterModelOptions(
            name='chatmembers',
            options={'verbose_name_plural': 'Chat Members'},
        ),
        migrations.AlterModelOptions(
            name='chatmessages',
            options={'verbose_name_plural': 'Chat Messages'},
        ),
        migrations.AlterModelTable(
            name='chat',
            table='chats',
        ),
        migrations.AlterModelTable(
            name='chatmembers',
            table='chat_members',
        ),
        migrations.AlterModelTable(
            name='chatmessages',
            table='chat_messages',
        ),
    ]
