# Generated by Django 3.0.4 on 2020-04-25 21:41

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lists', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('members', models.IntegerField(default=0, null=True)),
                ('shared_times', models.IntegerField(default=0, null=True)),
                ('is_open', models.BooleanField(default=False)),
                ('is_private', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Board',
                'db_table': 'boards',
            },
        ),
        migrations.CreateModel(
            name='BoardLists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.Board')),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lists.ShowsList')),
            ],
            options={
                'verbose_name': 'Board list',
                'db_table': 'board_lists',
            },
        ),
    ]
