# Generated by Django 3.0.4 on 2020-04-25 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='background_color',
            field=models.CharField(default=None, max_length=40, null=True),
        ),
    ]
