# Generated by Django 3.0.6 on 2020-06-26 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_boardmembers'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='background_image',
            field=models.FileField(default=None, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='board',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='board',
            name='tags',
            field=models.TextField(null=True),
        ),
    ]
