# Generated by Django 3.0.6 on 2020-06-27 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_auto_20200626_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='background_image',
            field=models.FileField(default=None, null=True, upload_to='../frontend/src/images'),
        ),
    ]
