# Generated by Django 3.0.6 on 2020-06-27 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0006_auto_20200627_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='background_image',
            field=models.FileField(default=None, null=True, upload_to='images/'),
        ),
    ]
