# Generated by Django 3.0.6 on 2020-06-27 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0008_boardfollowers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='members',
        ),
        migrations.AddField(
            model_name='board',
            name='followers',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
