# Generated by Django 3.0.6 on 2020-06-27 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0009_auto_20200627_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardfollowers',
            name='is_admin',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
