# Generated by Django 3.0.6 on 2020-06-27 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0010_boardfollowers_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='is_private',
        ),
    ]
