# Generated by Django 3.1.2 on 2020-11-07 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0011_remove_board_is_private'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='background_color',
        ),
        migrations.RemoveField(
            model_name='board',
            name='background_image',
        ),
    ]
