# Generated by Django 3.0.2 on 2020-01-26 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(default=None, verbose_name='Biographi'),
        ),
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(default=None, verbose_name='Birthday'),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.TextField(default=None, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='user',
            name='county',
            field=models.TextField(default=None, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.TextField(max_length=255, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.TextField(max_length=255, verbose_name='Last namme'),
        ),
    ]
