# Generated by Django 3.0.2 on 2020-01-26 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200126_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(null=True, verbose_name='Biographi'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(null=True, verbose_name='Birthday'),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.TextField(null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='user',
            name='county',
            field=models.TextField(null=True, verbose_name='Country'),
        ),
    ]
