# Generated by Django 3.0.4 on 2020-04-25 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200404_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.TextField(max_length=255, verbose_name='Last name'),
        ),
    ]
