# Generated by Django 3.0.6 on 2020-05-09 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200425_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.FileField(null=True, upload_to='', verbose_name='Photo'),
        ),
    ]
