# Generated by Django 3.0.6 on 2020-06-26 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20200606_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.FileField(null=True, upload_to='media/', verbose_name='Photo'),
        ),
    ]
