# Generated by Django 3.0.2 on 2020-01-26 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actors',
            fields=[
                ('actor_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('number_of_films', models.IntegerField(default=None)),
            ],
            options={
                'verbose_name_plural': 'Actors',
                'db_table': 'actors',
            },
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('country_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'db_table': 'countries',
            },
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('genre_id', models.AutoField(primary_key=True, serialize=False)),
                ('genre_name', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'Genres',
                'db_table': 'genres',
            },
        ),
        migrations.CreateModel(
            name='Shows',
            fields=[
                ('show_id', models.AutoField(primary_key=True, serialize=False)),
                ('name_rus', models.CharField(max_length=100)),
                ('name_eng', models.CharField(max_length=100)),
                ('showtype', models.CharField(max_length=100)),
                ('poster_url', models.CharField(blank=True, max_length=500, null=True)),
                ('imdb_rating', models.FloatField(blank=True, null=True)),
                ('users_rating', models.FloatField(default=0.0)),
                ('release_date', models.IntegerField()),
                ('plot', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Shows',
                'db_table': 'show',
            },
        ),
        migrations.CreateModel(
            name='ShowActors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='show.Actors')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='show.Shows')),
            ],
            options={
                'db_table': 'show_actors',
            },
        ),
        migrations.CreateModel(
            name='FilmGenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='show.Genres')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='show.Shows')),
            ],
            options={
                'db_table': 'show_genre',
            },
        ),
        migrations.CreateModel(
            name='FilmCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='show.Countries')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='show.Shows')),
            ],
            options={
                'db_table': 'show_country',
            },
        ),
    ]
