# Generated by Django 3.0.2 on 2020-01-29 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FilmCountry',
            new_name='ShowCountry',
        ),
        migrations.RenameModel(
            old_name='FilmGenre',
            new_name='ShowGenre',
        ),
    ]
