# Generated by Django 3.0.4 on 2020-03-28 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shows',
            name='users_rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
