# Generated by Django 3.0.4 on 2020-03-28 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0002_auto_20200328_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actors',
            name='number_of_films',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
