# Generated by Django 3.0.6 on 2020-05-10 21:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('show', '0003_auto_20200328_1846'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowRates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Rating')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='show.Shows')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'show_rates',
            },
        ),
    ]
