# Generated by Django 3.0.6 on 2020-08-30 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0005_remove_shows_users_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='shows',
            name='countries',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
