# Generated by Django 3.1.1 on 2020-09-28 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0007_auto_20200927_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='showreview',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='showreview',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
