# Generated by Django 3.0.4 on 2020-04-25 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0003_auto_20200328_1846'),
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListShow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lists.ShowsList')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='show.Shows')),
            ],
            options={
                'verbose_name': 'List show',
                'db_table': 'list_show_relations',
            },
        ),
    ]
