# Generated by Django 3.0.6 on 2020-05-12 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0005_remove_shows_users_rating'),
        ('lists', '0002_listshow'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ListShow',
            new_name='ListShowRelation',
        ),
    ]
