# Generated by Django 3.0.6 on 2020-05-17 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_auto_20200512_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='showslist',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
