# Generated by Django 3.1.2 on 2020-11-07 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shows_collections', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BoardMembers',
        ),
    ]
