# Generated by Django 3.1.2 on 2020-11-07 21:59

import datetime
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shows_collections', '0002_delete_boardmembers'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
        migrations.AddField(
            model_name='board',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='board',
            name='followers',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='board',
            name='is_open',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='board',
            name='name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='board',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='board',
            name='shared_times',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='board',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), null=True, size=None),
        ),
        migrations.AddField(
            model_name='list',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
        migrations.AddField(
            model_name='list',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='list',
            name='followers',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='list',
            name='is_open',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='list',
            name='name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='list',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='list',
            name='shared_times',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='list',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), null=True, size=None),
        ),
    ]
