# Generated by Django 3.1.2 on 2020-11-08 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shows_collections', '0003_auto_20201107_2159'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListFollowers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(default=False, null=True)),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shows_collections.list')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'List follower',
                'db_table': 'list_followers',
            },
        ),
    ]
