# Generated by Django 3.1.2 on 2020-11-08 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows_collections', '0004_listfollowers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='is_outside_board',
            field=models.BooleanField(default=True),
        ),
    ]
